[IMP] calendar_school: change Calendar Event Tree view
avanzosc/odoo-addons pull request #1046
Opened 2021-03-15 12:19 UTC by leiremartinezdesantos

2021-03-15 12:43 UTC, anajuaristi approved these changes

2021-03-15 13:02 UTC, oihane requested changes

2021-03-15 13:02 UTC, oihane commented on calendar_school/views/calendar_event_view.xml
> +                <field name="categ_ids" readonly="1" widget="many2many_tags" />
Si se pone readonly pierde el sentido de poder editar que se puso hace poco porque no podían crear manualmente las reuniones

2021-03-15 13:41 UTC, oihane commented on calendar_school/views/calendar_event_view.xml
> +            </xpath>
El tree editable al modulo custom

2021-03-15 15:17 UTC, oihane requested changes
Hay que ajustar los tests a los cambios realizados.

2021-03-16 15:52 UTC, oihane commented on calendar_school/views/calendar_event_view.xml
> +            <field name="stop" position="replace" />
este cambio tambien debe ir al personalizado

2021-03-17 10:17 UTC, alfredoavanzosc approved these changes
:+1:

2021-03-24 13:40 UTC, oihane approved these changes

2021-03-24 13:40 UTC, merged