[ADD] stock_picking_default_package: add default package for product …
avanzosc/odoo-addons pull request #1048
Opened 2021-03-22 12:59 UTC by leiremartinezdesantos

…category

2021-03-23 07:03 UTC, anajuaristi reviewed
Aldatu behar da objetua.

2021-03-23 07:03 UTC, anajuaristi commented on stock_picking_default_package/models/stock_move.py
> +    _inherit = "stock.move"
Ez da stock_MOVE baizik eta stock_move_line.

2021-03-24 12:14 UTC, alfredoavanzosc approved these changes
:+1

2021-04-08 10:22 UTC, Daniel-CA requested changes
Aldaketak dituzu beste modulu batzutan, egin rebase lehenengo.

2021-04-08 11:14 UTC, closed without merging