[ADD] website_event_custom: Custom fields in events.
avanzosc/odoo-addons pull request #1055
Opened 2021-03-26 11:26 UTC by alfredoavanzosc

2021-03-26 12:04 UTC, oihane requested changes

2021-03-26 12:04 UTC, oihane commented on website_event_custom/models/event_event.py
> +        string='Second Teacher', comodel_name='res.users')
Aunque se quiera establecer que son PROFESORES, lo más correcto seria ponerlos com responsables, haciendo que sea más genérico

2021-03-26 12:04 UTC, oihane commented on website_event_custom/models/event_event.py
> +                    actual_day = _('Sunday')
Haciendo un mapped del campo obtienes el listado de valores, luego los conviertes a su "nombre" en un listado y simplemente haciendo un join de esa lista puedes sacar el listado. Mucho más simple

2021-03-26 16:15 UTC, anajuaristi commented on website_event_custom/models/event_event.py
> +                    actual_day = _('Sunday')
Es decir, la tabla working hours YA TIENE esos nombres. No es necesario replicarlos.
Hay que evitar en la medida de lo posible, estos if "hardcode". No es buena práctica.

2021-03-26 16:16 UTC, anajuaristi commented on website_event_custom/models/event_event.py
> +        string='Second Teacher', comodel_name='res.users')
Main_responsible y second_responsible. Si. Es más correcto

2021-03-26 16:18 UTC, anajuaristi commented on website_event_custom/models/event_event.py
> +                    actual_day = _('Sunday')
NO OS olvideis del cambio de nombre de los módulos. 
Ya que vais a subir otro PR o este modificado, hacedlo ya con los nombres bien puestos.
Gracias!

2021-04-20 11:26 UTC, Berezi commented on website_event_custom/models/event_event.py
> +                    actual_day = _('Sunday')
Ya hemos dejado la programación en una linea:
my_text = ', '.join(distinct(attendance_ids.mapped('dayofweek')))
Pero como resultado nos muestra:
0, 1, 2, 3, 4
No encontramos ningún ejemplo que nos convierta, o coja el texto.

2021-04-21 06:42 UTC, alfredoavanzosc commented
Cerramos este PR que es sustituido por https://github.com/avanzosc/odoo-addons/pull/1065

2021-04-21 06:42 UTC, closed without merging