[ADD] event_create_track: When the stage of the event is announced, c…
avanzosc/odoo-addons pull request #1093
Opened 2021-05-06 11:58 UTC by Berezi

…reate track.

2021-05-06 11:59 UTC, Berezi commented
@alfredoavanzosc @oihane @Daniel-CA @anajuaristi

2021-05-06 14:38 UTC, oihane commented on event_create_track/models/event_event.py
> +            fields.Datetime.to_string(my_date), '%Y-%m-%d %H:%M:%S')
Es esto realmente necesario??

2021-05-10 11:30 UTC, Berezi commented on event_create_track/models/event_event.py
> +            fields.Datetime.to_string(my_date), '%Y-%m-%d %H:%M:%S')
Sí porque la hora viene así: 06:00:00+00:00. Y hay que convertirlo.

2021-05-11 13:30 UTC, anajuaristi approved these changes

2021-05-11 13:31 UTC, anajuaristi commented
@avanzosc/developers review please

2021-05-11 15:23 UTC, oihane commented on event_create_track/models/event_event.py
> +            fields.Datetime.to_string(my_date), '%Y-%m-%d %H:%M:%S')
usando esto podrías quitar esa parte, my_date.replace(tzinfo=None)

2021-05-11 15:25 UTC, oihane requested changes
Si usas **fields.Datetime.to_string** para convertir a string un datetime, puedes usa a la inversa, **fields.Datetime.from_string** que usa el formato de odoo para las fechas **DATETIME_FORMAT**

2021-05-12 08:11 UTC, anajuaristi approved these changes

2021-05-12 08:11 UTC, alfredoavanzosc approved these changes
:+1:

2021-05-12 10:47 UTC, oihane approved these changes

2021-05-12 12:08 UTC, merged