[ADD] project_task_service_partner: Create date in res partner and pr…
avanzosc/odoo-addons pull request #1122
Opened 2021-05-27 12:42 UTC by Berezi

…oject task. Patient in project and task.

2021-05-27 12:43 UTC, Berezi commented
@alfredoavanzosc @anajuaristi @Daniel-CA @oihane review please.

2021-06-22 08:05 UTC, anajuaristi commented on project_task_service_partner/models/project_task.py
> +        related='sale_order_id.partner_shipping_id')
related='project_id.partner_shipping_id')

2021-06-22 08:05 UTC, anajuaristi commented on project_task_service_partner/views/project_project_views.xml
> +        <field name="inherit_id" ref="sale_timesheet.project_project_view_form"/>
ref="project_project_view_form"/>

2021-06-22 08:05 UTC, anajuaristi commented on project_task_service_partner/views/project_project_views.xml
> +    <record id="view_project" model="ir.ui.view">
project_project_view_tree

2021-06-22 08:05 UTC, anajuaristi commented on project_task_service_partner/views/project_task_views.xml
> +        <field name="inherit_id" ref="project.view_task_form2"/>
project.view_task_form

2021-06-22 08:05 UTC, anajuaristi commented on project_task_service_partner/views/project_task_views.xml
> +        <field name="inherit_id" ref="project.view_task_tree2"/>
project.view_task_tree

2021-06-22 10:39 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc  review please.

2021-06-22 13:06 UTC, oihane requested changes
El rebase no es correcto, no se puede mergear como está

2021-06-23 08:43 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-06-23 12:55 UTC, oihane commented
Este modulo tiene que ir a la rama project-addons

2021-06-23 12:55 UTC, closed without merging