[ADD] event_website_visibility: limit website event visibility
avanzosc/odoo-addons pull request #1143
Opened 2021-06-10 08:20 UTC by leiremartinezdesantos

2021-06-10 10:51 UTC, oihane requested changes
FLAKE8
```
event_website_visibility/models/event.py:2:1: F401 'odoo.api' imported but unused
event_website_visibility/models/event.py:2:1: F401 'odoo.tools' imported but unused
event_website_visibility/models/event.py:2:1: F401 'odoo._' imported but unused
event_website_visibility/models/event.py:11:80: E501 line too long (83 > 79 characters)
event_website_visibility/models/event.py:15:80: E501 line too long (99 > 79 characters)
event_website_visibility/models/event.py:16:1: W391 blank line at end of file
event_website_visibility/controllers/main.py:2:1: F401 'odoo._' imported but unused
event_website_visibility/controllers/main.py:16:80: E501 line too long (102 > 79 characters)
event_website_visibility/controllers/main.py:36:80: E501 line too long (90 > 79 characters)
event_website_visibility/controllers/main.py:43:1: W391 blank line at end of file
```

PYLINT
```
event_website_visibility/__init__.py:1: [C7902(missing-readme), ] Missing ./README.rst file. Template here: https://github.com/OCA/maintainer-tools/blob/master/template/module/README.rst
```

2021-06-17 13:57 UTC, oihane commented
No falta la ACL que para "Solo miembros"?

2021-06-17 14:01 UTC, leiremartinezdesantos commented
> miembros

Nun?

2021-06-21 12:46 UTC, oihane commented
> > miembros
> 
> Nun?

Parecido a https://github.com/OCA/OCB/blob/14.0/addons/project/security/project_security.xml#L72

2021-06-21 14:10 UTC, leiremartinezdesantos commented
Baño los eventos pueden ser públicos

2021-06-21 14:15 UTC, oihane commented
Pero si son de miembros, debería de estar limitado a miembros y eso no lo recoje ninguna ACL, o regla de acceso.

2021-06-29 09:14 UTC, oihane commented
Necesita REBASE

2021-06-29 09:14 UTC, oihane approved these changes

2021-06-29 12:13 UTC, merged