[IMP] event_registration_student: Put one related store equal to true.
avanzosc/odoo-addons pull request #1145
Opened 2021-06-11 07:49 UTC by Berezi

2021-06-11 07:52 UTC, Berezi commented
@anajuaristi @alfredoavanzosc @oihane @Daniel-CA review please.

2021-06-11 08:16 UTC, oihane commented on event_registration_student/models/event_registration.py
> +        help=_('Invoicing start date.'))
Esto no se hace así, solo poniendo `help` es suficiente.

2021-06-11 08:17 UTC, oihane commented on event_registration_student/models/event_registration.py
> +        return True
Esto lo tuvo que cambiar alfredo, si pones True falla

2021-06-11 08:20 UTC, oihane requested changes
Para hacer un `store=True`, has cambiado muchas cosas más, tienes que revisar. Que solo subes el cambio.

2021-06-11 11:49 UTC, oihane approved these changes

2021-06-14 06:24 UTC, alfredoavanzosc approved these changes
:+1

2021-06-14 08:49 UTC, merged