[ADD] account_invoice_report_show_payment_reference: In payment modes…
avanzosc/odoo-addons pull request #1155
Opened 2021-06-18 07:49 UTC by alfredoavanzosc

… new field "Print payment reference in invoices".
@avanzosc/developers ... review please.

2021-06-22 13:48 UTC, oihane requested changes, later dismissed
Hay que hacer rebase

2021-06-22 13:48 UTC, oihane commented on account_invoice_report_show_payment_reference/__manifest__.py
> +        "account_payment_mode",
Falta la dependencia con account

2021-06-23 07:17 UTC, oihane commented
Si usas una vista o qweb como has hecho en este caso, es recomendable, existe la remota posibilidad de que hiciesen esos independientes (cosa que no tendría sentido) y por ello es mejor. Si usas, algún permiso especifico, grupo o cosas así también conviene.
No lo he mirado aún.

2021-06-23 14:04 UTC, mikelarre approved these changes

2021-06-23 14:09 UTC, Daniel-CA approved these changes

2021-06-23 14:09 UTC, merged