[ADD] meeting_timesheet_analytic: When the meeting is realized, input…
avanzosc/odoo-addons pull request #1172
Opened 2021-06-30 11:08 UTC by Berezi

…s time sheet hours.

2021-06-30 11:08 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-06-30 14:46 UTC, oihane requested changes
cambiar el nombre a calendar_timesheet

2021-06-30 15:52 UTC, oihane commented on meeting_timesheet_analytic/README.rst
> +* When the meeting is realized, inputs time sheet hours.
Cuando la reunión se da cuenta, introduce partes de hora

When the meeting is set done, it creates timesheets.

2021-06-30 16:05 UTC, oihane requested changes

2021-06-30 16:05 UTC, oihane commented on meeting_timesheet_analytic/models/project_task.py
> +        return super(ProjectTask, self).write(vals)
SOBRA

2021-06-30 16:05 UTC, oihane commented on meeting_timesheet_analytic/models/account_analytic_line.py
> +        return super(AccountAnalyticLine, self).write(vals)
SOBRA

2021-06-30 16:05 UTC, oihane commented on meeting_timesheet_analytic/models/calendar_event.py
> +            ("realized", "Realized"),
REALIZADO = DONE

2021-06-30 16:05 UTC, oihane commented on meeting_timesheet_analytic/models/calendar_event.py
> +            'project_id': self.task_id.project_id.id,
Si el proyecto va con la tarea, y estas haciendo luego el control de la tarea... esto debería ir con ello.

2021-06-30 16:05 UTC, oihane commented on meeting_timesheet_analytic/models/calendar_event.py
> +            'account_id': self.task_id.project_id.analytic_account_id.id}
Si no hay tarea no hay proyecto no hay cuenta analítica

2021-07-02 11:11 UTC, Berezi commented
@anajuaristi @oihane @alfredoavanzosc @Daniel-CA review please.

2021-07-05 07:47 UTC, oihane commented on calendar_timesheet/models/calendar_event.py
> +            ("realized", "Done"),
realized no significa HECHO

2021-07-05 07:48 UTC, oihane commented on calendar_timesheet/models/calendar_event.py
> +                        duration = duration + line.hour_gap
duration = sum(lines.mapped("hour_gap")

2021-07-06 09:19 UTC, anajuaristi approved these changes

2021-07-06 11:36 UTC, oihane approved these changes

2021-07-06 11:37 UTC, merged