[MIG] resource_time: With this module you can watch the time gap in r…
avanzosc/odoo-addons pull request #1173
Opened 2021-07-01 09:10 UTC by Berezi

…esource working time

2021-07-01 09:10 UTC, Berezi commented
@anajuaristi @alfredoavanzosc @Daniel-CA @oihane review please.

2021-07-01 09:12 UTC, oihane requested changes
No se ha migrado siguiendo los pasos de migraciones, se puede ver que solo tiene un único commit y debería de tener 6

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-14.0#howto

2021-07-01 11:30 UTC, Daniel-CA commented on resource_time/__manifest__.py
> +    "version": "12.0.1.1.0",
Tienes que actualizar a la versión que corresponde: 14.0.1.0.0

2021-07-06 07:14 UTC, Daniel-CA approved these changes

2021-07-06 07:43 UTC, oihane approved these changes

2021-07-06 07:43 UTC, alfredoavanzosc approved these changes
:+1:

2021-07-06 07:44 UTC, merged