[ADD] product_packaging_dimension: Set the package dimension fields a…
avanzosc/odoo-addons pull request #1369
Opened 2021-12-16 14:37 UTC by Berezi

…s floating and set the unit as eligible.

2021-12-16 14:38 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-12-16 15:40 UTC, Daniel-CA requested changes
product_packaging_dimension  ya existe

https://github.com/OCA/product-attribute/tree/14.0/product_packaging_dimension

2021-12-17 09:36 UTC, Berezi commented
@Daniel-CA izena aldauta. Eskerrik asko.

2021-12-17 10:15 UTC, alfredoavanzosc approved these changes
:+1:

2021-12-17 11:55 UTC, Daniel-CA commented
El módulo product_packaging_volume hay que modificarlo para hacerlo compatible con el product_packaging_dimension ya que son incompatibles tal y como están ahora:

https://github.com/avanzosc/odoo-addons/blob/14.0/product_packaging_volume/models/stock_move_line.py#L12

Revisar si el "product_packaging_dimension" cumple ya los requerimientos y eliminarlos de "product_packaging_volume"

2021-12-20 12:39 UTC, closed without merging