[IMP] product_packaging_volume
avanzosc/odoo-addons pull request #1371
Opened 2021-12-20 12:36 UTC by Berezi

2021-12-20 12:36 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc review please.

2021-12-20 13:01 UTC, Daniel-CA requested changes

2021-12-20 13:01 UTC, Daniel-CA commented on product_packaging_volume/models/product_packaging.py
> +    packaging_length = fields.Float("Length")
product_packaging_dimension ya tiene definidos esos campos, no hace falta volver a definirlos.

https://github.com/OCA/product-attribute/blob/14.0/product_packaging_dimension/models/product_packaging.py#L22

2021-12-20 13:46 UTC, Berezi commented on product_packaging_volume/models/product_packaging.py
> +    packaging_length = fields.Float("Length")
Es que si no pongo eso me dice que hay inconsistencias. No sé porque...

2021-12-20 13:56 UTC, Berezi commented on product_packaging_volume/models/product_packaging.py
> +    packaging_length = fields.Float("Length")
Parece que como el módulo product_packaging_dimension no tiene dependencia de delivery, al instalar los dos a la vez, no hace el cambio a float. Sin embargo, si instalas primero delivery y después el product_packaging_dimension, entonces si que hace el cambio a float. Sino, ¿cómo podría solucionar esto?

2022-01-10 11:09 UTC, Daniel-CA commented on product_packaging_volume/models/product_packaging.py
> +    packaging_length = fields.Float("Length")
El problema tal y como comentas proviene del módulo "delivery" y el módulo "product_packaging_dimension".
Los dos definen los mismos campos para el mismo objeto y para el primero los campos son integer y para el segundo float de ahí que se estén chocando tal y como comentan aquí:
https://github.com/OCA/product-attribute/pull/957

Si este módulo tiene que convivir con los dos hay que poner los campos que sean en compute y utilizar el método "inverse" para evitar estos problemas tal y como apuntan al final del hilo.

2022-01-10 14:14 UTC, closed without merging