[ADD] stock_production_lot_mother: Birth rate, laying rate and lineag…
avanzosc/odoo-addons pull request #1399
Opened 2022-01-17 14:18 UTC by Berezi

…e new three objects in stock production lot.

2022-01-17 14:19 UTC, Berezi commented
@anajuaristi @oihane @Daniel-CA @alfredoavanzosc  review please.

2022-01-17 18:23 UTC, anajuaristi requested changes

2022-01-17 18:23 UTC, anajuaristi commented on stock_production_lot_mother/views/lineage_views.xml
> +                        <page string="Birth Rate" name="birth_rate">
Incluir domain donde mother_id sea nulo.

2022-01-17 18:23 UTC, anajuaristi commented on stock_production_lot_mother/views/lineage_views.xml
> +                        <page string="Laying Rate" name="laying_rate">
incluir domain done mother_id sea nulo

2022-01-17 18:23 UTC, anajuaristi commented on stock_production_lot_mother/views/stock_production_lot_views.xml
> +                    <button name="button_bring_lineage_birth_rate" type="object" string="Bring Lineage Birth Rate"/>
Quitar los 2 botones y dejar solo uno.
Con un solo click debería traer las 2 tablas la de nacimiento y la de puesta.
Subir botón arriba al lote y crear action para poder llamar al botón desde el tree y crear las líneas para varias madres a la vez.

2022-01-17 18:23 UTC, anajuaristi commented on stock_production_lot_mother/models/stock_production_lot.py
> +    def button_bring_lineage_birth_rate(self):
Quitar uno de los 2 buttons
Crear action para llamar a la funciona button_bring_lineage_rates

2022-01-17 18:23 UTC, anajuaristi commented on stock_production_lot_mother/models/stock_production_lot.py
> +                lot.birth_rate_ids = lot.lineage_id.birth_rate_ids.ids
No es correcto, ya que lo que hace es asignar el número de madre a líneas existentes y por tanto, no crea nuevas líneas para cada madre.
La función correcta sería algo así como 
```
For lot in self:
   if lot.lineage_nacimiento
      for line in lineage_nacimiento
           crear líneas madre --> Copiar/duplicar la línea de nacimiento asociando el id de la madre
   if lot.lineage_puesta
       for line in lineage_puesta
           crear líneas madre --> Copiar/duplicar la línea de puesta asociando el id de la madre
```

2022-01-19 14:21 UTC, anajuaristi commented on stock_production_lot_mother/models/lineage.py
> +    birth_rate_ids = fields.One2many(
Domain mother = False

2022-01-19 14:21 UTC, anajuaristi commented on stock_production_lot_mother/models/lineage.py
> +    mother_ids = fields.One2many(
Jarri vista bat hoiek erakusteko o shortcut but

2022-01-19 14:21 UTC, anajuaristi commented on stock_production_lot_mother/models/stock_production_lot.py
> +                lot.closing_weeks = 0
Gora eman

2022-01-19 14:21 UTC, anajuaristi commented on stock_production_lot_mother/models/stock_production_lot.py
> +                            'week': rate.week,
Kendu percentage. 
Bilaketa mother eta week. Besteak soberan daude

2022-01-25 11:53 UTC, Daniel-CA approved these changes

2022-01-31 15:23 UTC, anajuaristi approved these changes

2022-01-31 15:23 UTC, merged