[IMP] event_schedule: In events new fields "Copy main responsible" an…
avanzosc/odoo-addons pull request #1421
Opened 2022-02-01 14:54 UTC by alfredoavanzosc

…d "Copy second responsible".

2022-02-01 14:54 UTC, alfredoavanzosc commented
@avanzosc/developers ... review please

2022-02-01 16:14 UTC, anajuaristi approved these changes

2022-02-01 17:00 UTC, oihane commented on event_schedule/models/event_event.py
> +        return super(EventEvent, self).copy(default)
Habría que poner todo esto después del último campo no entre medias.

Además yo haría que el los many2one sean copy=false. y que si estos campos tienen valor, entonces se añadan en el default.

2022-02-02 06:53 UTC, alfredoavanzosc commented on event_schedule/models/event_event.py
> +        return super(EventEvent, self).copy(default)
Eskerrik asko @oihane , ya he realizado las mejoras que me has solicitado.

2022-02-02 08:54 UTC, oihane requested changes, later dismissed

2022-02-02 08:54 UTC, oihane commented on event_schedule/i18n/es.po
> +. module: event_schedule
Repito, tienes un error en este fichero

2022-02-02 11:14 UTC, anajuaristi approved these changes

2022-02-02 15:44 UTC, Daniel-CA approved these changes

2022-02-03 08:11 UTC, merged