[14.0][IMP] product_editable_tree_menu: Standard price also editable.
avanzosc/odoo-addons pull request #1615
Opened 2022-06-22 10:15 UTC by Berezi

2022-06-22 10:15 UTC, Berezi commented
@anajuaristi @oihane @alfredoavanzosc review please.

2022-06-22 10:41 UTC, oihane requested changes
Este cambio no lleva a nada.

```xml
<attribute name="readonly" />
```
Eso borra el parámetro, y por lo que veo en mi local el campo se puede modificar.

2022-06-22 10:54 UTC, anajuaristi approved these changes

2022-06-29 15:53 UTC, anajuaristi approved these changes

2022-07-27 09:24 UTC, anajuaristi approved these changes, later dismissed

2023-04-19 06:20 UTC, closed without merging