[IMP] product_usability: Show "incoming_qty", and "outgoing_qty", in …
avanzosc/odoo-addons pull request #1737
Opened 2022-09-29 06:45 UTC by alfredoavanzosc

…product template form, and tree views.

2023-05-30 11:51 UTC, oihane requested changes, later dismissed

2023-05-30 11:51 UTC, oihane commented on product_usability/models/product_product.py
> +        search="_search_product_pricelist")
Esto no hace más que dar error

2023-05-30 11:51 UTC, oihane commented on product_usability/models/product_template.py
> +        search="_search_product_pricelist")
Esto no hace más que dar error

2023-06-20 08:15 UTC, alfredoavanzosc commented on product_usability/models/product_template.py
> +        search="_search_product_pricelist")
solucionado. Eskerrik asko.

2023-06-26 07:23 UTC, anajuaristi approved these changes

2023-06-26 07:23 UTC, merged