[ADD] stock_picking_batch_usability: In form view of object "Batch Tr…
avanzosc/odoo-addons pull request #1798
Opened 2022-12-13 13:02 UTC by alfredoavanzosc

…ansfer", two new shorcusts to: "Delivery" and "Sale Orders".

2022-12-13 13:11 UTC, alfredoavanzosc commented
CLM5510

2022-12-13 13:49 UTC, oihane commented
Un modulo de "usabilidad" no debería instalar un modulo que no sea SOLO de stock

2022-12-13 14:10 UTC, alfredoavanzosc commented
Al final el módulo se llama "stock_picking_batch_shortcut".

2022-12-13 14:13 UTC, oihane requested changes, later dismissed

2022-12-13 14:13 UTC, oihane commented on stock_picking_batch_shortcut/README.rst
> +* Berezi Amubieta <bereziamubieta@avanzosc.es>
Contributor serías tu no berezi

2022-12-13 14:13 UTC, oihane commented on stock_picking_batch_shortcut/__manifest__.py
> +        "sale",
La dependencia no es correcta

2022-12-13 14:16 UTC, oihane commented
No has modificado el *.pot

2022-12-13 14:41 UTC, oihane submitted a review, later dismissed
Las dependencias siguen siendo incorrectas.

2022-12-13 14:47 UTC, alfredoavanzosc commented
@oihane ... no entiendo porqué dices que las dependencias siguen siendo erróneas. Sólo tiene dependencia con "stock_picking_batch".

2022-12-13 16:35 UTC, anajuaristi commented on stock_picking_batch_shortcut/__manifest__.py
> +        "sale",
sale_stock

2022-12-20 09:49 UTC, anajuaristi approved these changes

2022-12-20 09:50 UTC, merged