[14.0][ADD] custom_breeding_report: Breeding reports.
avanzosc/odoo-addons pull request #2050
Opened 2023-07-21 09:57 UTC by Berezi

2023-11-23 10:28 UTC, oihane requested changes
```
2023-11-23 10:27:14,015 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_mother_lineage_relation_xlsx'.
  warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
 
2023-11-23 10:27:14,027 3725011 INFO pt_20220919B_copia2610b odoo.modules.loading: loading custom_breeding_report/report/lineage_percentage_report_xlsx.xml 
2023-11-23 10:27:14,030 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_lineage_percentage_xlsx'.
  warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
 
2023-11-23 10:27:14,038 3725011 INFO pt_20220919B_copia2610b odoo.modules.loading: loading custom_breeding_report/report/stock_picking_batch_report_xlsx.xml 
2023-11-23 10:27:14,041 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_stock_picking_batch_xlsx'.
  warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
 
2023-11-23 10:27:14,048 3725011 INFO pt_20220919B_copia2610b odoo.modules.loading: loading custom_breeding_report/report/breeding_general_summary_xlsx.xml 
2023-11-23 10:27:14,053 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_breeding_general_summary_xlsx'.
  warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)

```

2023-11-23 11:16 UTC, Berezi commented
> ```
> 2023-11-23 10:27:14,015 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_mother_lineage_relation_xlsx'.
>   warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
>  
> 2023-11-23 10:27:14,027 3725011 INFO pt_20220919B_copia2610b odoo.modules.loading: loading custom_breeding_report/report/lineage_percentage_report_xlsx.xml 
> 2023-11-23 10:27:14,030 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_lineage_percentage_xlsx'.
>   warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
>  
> 2023-11-23 10:27:14,038 3725011 INFO pt_20220919B_copia2610b odoo.modules.loading: loading custom_breeding_report/report/stock_picking_batch_report_xlsx.xml 
> 2023-11-23 10:27:14,041 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_stock_picking_batch_xlsx'.
>   warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
>  
> 2023-11-23 10:27:14,048 3725011 INFO pt_20220919B_copia2610b odoo.modules.loading: loading custom_breeding_report/report/breeding_general_summary_xlsx.xml 
> 2023-11-23 10:27:14,053 3725011 WARNING pt_20220919B_copia2610b py.warnings: /opt/odoo/v14/core/odoo/tools/convert.py:296: DeprecationWarning: The <report> tag is deprecated, use a <record> tag for 'report_breeding_general_summary_xlsx'.
>   warnings.warn(f"The <report> tag is deprecated, use a <record> tag for {xml_id!r}.", DeprecationWarning)
> ```

Zuzenduta. Eskerrikasko.

2023-11-24 09:09 UTC, oihane commented on custom_breeding_report/report/breeding_general_summary_xlsx.xml
> +    <data>
Esto no es necesario

2023-11-24 12:00 UTC, oihane commented on custom_breeding_report/report/stock_picking_batch_xlsx.py
> +_logger = logging.getLogger(__name__)
No se usa

2023-11-24 12:07 UTC, Berezi commented on custom_breeding_report/report/stock_picking_batch_xlsx.py
> +_logger = logging.getLogger(__name__)
Kenduta. Mertzi

2023-12-27 09:47 UTC, anajuaristi approved these changes

2023-12-27 09:51 UTC, anajuaristi approved these changes

2024-01-05 09:09 UTC, merged