[IMP] purchase_order_line_input: In purchase lines new fields: "Sourc…
avanzosc/odoo-addons pull request #2069
Opened 2023-08-04 05:02 UTC by alfredoavanzosc

…e Document", and "Vendor Reference".

2023-08-04 05:02 UTC, alfredoavanzosc commented
CLM7510

2023-08-04 08:06 UTC, oihane requested changes

2023-08-04 08:06 UTC, oihane commented on purchase_order_line_input/views/purchase_order_line_view.xml
> -            <field name="product_uom" groups="uom.group_uom" />
NO eliminar esos campos de búsqueda.

2023-08-04 08:42 UTC, alfredoavanzosc commented on purchase_order_line_input/views/purchase_order_line_view.xml
> -            <field name="product_uom" groups="uom.group_uom" />
Solucionado. Eskerrik asko.

2023-12-28 12:15 UTC, anajuaristi approved these changes

2023-12-28 12:17 UTC, anajuaristi approved these changes

2024-07-23 13:00 UTC, oihane approved these changes

2024-07-24 12:21 UTC, closed without merging