[14.0][IMP] product_import_wizard:
avanzosc/odoo-addons pull request #2227
Opened 2023-11-10 09:48 UTC by Berezi

2023-11-14 15:46 UTC, oihane requested changes

2023-11-14 15:46 UTC, oihane commented on product_import_wizard/models/product_import.py
> +            "company_id": self.self.import_id.company_id.id,
Esto aparte de estar mal, si se hace una actualización de productos, lo pondrá en la compañia, aunque estuviese disponible en un entorno multicompañia, harías que se asigne a una única compañia.

2023-11-28 14:54 UTC, Berezi commented on product_import_wizard/models/product_import.py
> +            "company_id": self.self.import_id.company_id.id,
Kenduta. Eskerrikasko

2023-12-27 09:37 UTC, anajuaristi approved these changes

2023-12-27 09:39 UTC, anajuaristi approved these changes

2024-01-08 12:29 UTC, merged