[ADD] purchase_order_type_partner: In partners, show "Purchase type".
avanzosc/odoo-addons pull request #2233
Opened 2023-11-20 08:14 UTC by alfredoavanzosc

2023-11-20 08:14 UTC, alfredoavanzosc commented
CLM8237

2023-11-20 14:05 UTC, oihane requested changes

2023-11-20 14:05 UTC, oihane commented on purchase_order_type_partner/models/res_partner.py
> +        states=Purchase.READONLY_STATES,
Esto no tiene ningun sentido.

2023-11-21 06:38 UTC, alfredoavanzosc commented on purchase_order_type_partner/models/res_partner.py
> +        states=Purchase.READONLY_STATES,
Tema solucionado. Eskerrik asko.

2024-07-24 10:21 UTC, closed without merging