[16.0][ADD] ir_module_compare_wizard
avanzosc/odoo-addons pull request #2317
Opened 2024-01-05 11:10 UTC by unaiberis

Upload al list of modules with a file to check whether they exists or not and if in case
that they exist if they are also installed or not.

2024-01-05 11:19 UTC, oihane requested changes
No se ha eliminado el fichero ir_module_views.xml

2024-01-05 12:05 UTC, oihane submitted a review, later dismissed

2024-01-05 12:05 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +            record.module_count = len(record.import_line_ids)
Cuentas líneas no modulos:

```python
record.module_count = len(record.mapped("import_line_ids.import_module_id")
```

2024-01-05 12:28 UTC, oihane commented on ir_module_compare_wizard/__manifest__.py
> +    "name": "Module Compare Wizard",
Este nombre deberia de coincidir con el del readme

2024-01-05 12:29 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +            record.module_count = len(record.mapped("import_line_ids.import_module_id")
Falta un parentesis, esto hará que de traceback

2024-01-05 12:31 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +        if self.module_technical_name:
Si es el campo requerido para crear una linea, este IF sobra

2024-01-05 12:32 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +        if not modules:
Porque si no esto va a fallar

2024-01-05 12:32 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +            )
NO se necesita este AND, no estas cogiendo un dominio que existe y añadiéndole algo con un AND

2024-01-05 12:33 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +        lot = False
¿¿¿¿LOT???

2024-01-05 13:04 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +            if not module_technical_name:
NOOOOOO, esto despues de cogerlo de row_values!

2024-01-05 13:10 UTC, oihane commented on ir_module_compare_wizard/models/ir_module_compare.py
> +        if row_values:
```python
module_technical_name = row_values.get("Name", False)
if not module_technical_name:
    return {}
```

Primero darle valor a la variable, y luego "usarla" si no va  a dar traceback. Esto hace que si no hay "Name" en el excel (o csv) no cree la línea que es por lo que luego el control de valor en ese campo no es necesario.

2024-01-10 13:21 UTC, oihane commented
https://github.com/avanzosc/odoo-addons/blob/16.0/contacts_import_wizard/views/res_partner_import_views.xml#L93

Usando eso de ejemplo, cambiar el texto de la ayuda, ya que hace traducciones que no recoge el .po y luego lleva a error al hacer la carga.

2024-01-12 11:21 UTC, oihane commented on ir_module_compare_wizard/views/ir_module_import_views.xml
> +                                        <li><code t-translation="off">Last Version</code>: this will fill <b
Lo que está dentro de lo de <code> debe coincidir con los nombres usados para obtener las lineas. En este caso LastVersion, sin espacio. La idea es que la cabecera del excel / csv sean los campos en code. Y aquello que esta dentro de la etiqueta <b> sea igual al nombre del campo que se rellena.

2024-01-12 11:30 UTC, oihane reviewed
En el objeto `ir.module.import` habría que añadir lo siguiente:
```python
    def action_validate(self):
        self.env['ir.module.module'].update_list()
        return super().action_validate()
```

Que actualizará la lista de módulos, antes de hacer la comprobación.

2024-01-26 10:22 UTC, anajuaristi approved these changes

2024-01-26 11:02 UTC, merged