[14.0][IMP] custom_descarga:
avanzosc/odoo-addons pull request #2343
Opened 2024-01-17 14:06 UTC by Berezi

2024-01-18 11:00 UTC, oihane requested changes
Se han eliminado todos los ajustes que ha realizado el pre-commit. Revisar y añadir únicamente los cambios reales. Hay muchos cambios que no son realmente necesarios.

2024-01-23 09:00 UTC, Berezi commented
> Se han eliminado todos los ajustes que ha realizado el pre-commit. Revisar y añadir únicamente los cambios reales. Hay muchos cambios que no son realmente necesarios.
Zuzenduta eskerrikasko.

2024-01-24 12:48 UTC, oihane commented on custom_descarga/models/saca_line.py
> +        selection="_get_selection_color",
Si es related no es necesario el selection, odoo te lo indica

2024-01-24 12:49 UTC, oihane commented
Falta que el commit indique que es lo que se ha ampliado.

2024-02-06 14:39 UTC, anajuaristi approved these changes

2024-02-15 07:46 UTC, oihane approved these changes

2024-02-15 08:39 UTC, anajuaristi approved these changes

2024-02-15 08:39 UTC, merged