[16.0][IMP] product_usability:
avanzosc/odoo-addons pull request #2349
Opened 2024-01-19 12:37 UTC by Berezi

2024-01-22 08:44 UTC, oihane requested changes
Hay que cambiar siempre sobre la ultima versión y revista que solo se vayan a aplicar los cambios que se han hecho.
Además de que estás cambiando cosas que están corregidas con el pre-commit.

2024-01-22 08:44 UTC, oihane commented on product_usability/__manifest__.py
> +    "version": "14.0.1.2.0",
Si es para v16 esto no se debe cambiar

2024-01-22 08:44 UTC, oihane commented on product_usability/__manifest__.py
> +    "website": "http://www.avanzosc.es",
No cambiar

2024-01-22 10:21 UTC, oihane commented on product_usability/tests/common.py
> +class ProductUsabilityCommon(common.SavepointCase):
Esto falla, SavepointCase no existe

2024-01-22 15:37 UTC, Berezi commented on product_usability/__manifest__.py
> +    "version": "14.0.1.2.0",
Zuzenduta. Eskerrikasko.

2024-01-22 15:37 UTC, Berezi commented on product_usability/__manifest__.py
> +    "website": "http://www.avanzosc.es",
Zuzenduta

2024-01-22 15:37 UTC, Berezi commented on product_usability/tests/common.py
> +class ProductUsabilityCommon(common.SavepointCase):
Zuzenduta

2024-07-29 10:17 UTC, anajuaristi approved these changes

2024-07-29 10:23 UTC, oihane approved these changes

2024-07-29 15:48 UTC, merged