[ADD] product_supplierinfo_certification: New object "Certifications"…
avanzosc/odoo-addons pull request #2512
Opened 2024-04-25 09:39 UTC by alfredoavanzosc

… Suppliers.

2024-04-25 09:39 UTC, alfredoavanzosc commented
CLM9017

2024-04-25 15:22 UTC, oihane requested changes
PR MAL SUBIDO

2024-08-02 08:12 UTC, anajuaristi approved these changes

2024-08-02 08:12 UTC, anajuaristi commented on product_supplierinfo_certification/views/res_partner_views.xml
> +                    <field name="certification_id"
Quita el invisible. Que se vea siempre y se pueda asignar siempre.

2024-08-02 08:21 UTC, closed without merging