[ADD] account_analytic_invoicing
avanzosc/odoo-addons pull request #299
Opened 2016-09-15 11:05 UTC by esthermm

2016-09-15 15:50 UTC, anajuaristi commented
No me gusta mucho el nombre del módulo porque no indica lo que hace.
```
If you create a recurring invoice from contracts, this module create the invoice
 +  with payment term, payment mode and bank value of the partner.
```
¿qué tal account_analytic_payment_data_on_invoice?
O, ¿account_analytic_partner_data_on_invoice?
¿Otro que se os ocurra?
@oihane @agaldona

2016-09-16 07:59 UTC, oihane commented
`account_analytic_partner_invoicing`

2016-09-16 08:00 UTC, oihane commented on account_analytic_invoicing/models/account_analytic.py
> +    def _recurring_create_invoice(self, automatic=False):
Deberías de hacer estos cambios en https://github.com/OCA/OCB/blob/8.0/addons/account_analytic_analysis/account_analytic_analysis.py#L670
de manera que la factura los incluya cuando se cree y no que los escribas.

2016-09-16 08:01 UTC, oihane requested changes
Tal vez este modulo debiera de ser propuesto a OCA, pero no sé a cual de las ramas :worried:

2016-09-20 11:00 UTC, esthermm commented on account_analytic_invoicing/models/account_analytic.py
> +    def _recurring_create_invoice(self, automatic=False):
Para hacer los cambios en el core, habría que poner el account_analytic_analysis dependiente de account_payment_partner

2016-09-20 13:43 UTC, oihane commented on account_analytic_invoicing/models/account_analytic.py
> +    def _recurring_create_invoice(self, automatic=False):
Me has entendido mal, me refiero a que extiendas ese método :wink:

2016-09-20 13:50 UTC, closed without merging