[FIX] account_analytic_analysis_recurring_day: Fix when create/modify…
avanzosc/odoo-addons pull request #313
Opened 2016-10-17 10:56 UTC by alfredoavanzosc

… account where recurring_first_day is true.
Arreglar error cuando se crea, o modificar una cuenta analítica, cuando se indica en su creación/modificación que se debe de generar el primer día de cada mes.

2016-10-17 13:15 UTC, alfredoavanzosc commented
@agaldona , @Daniel-CA .. ¿Le podéis echar un vistazo?. Eskerrik asko.

2016-10-18 08:38 UTC, agaldona requested changes

2016-10-18 08:38 UTC, agaldona commented on account_analytic_analysis_recurring_day/models/account_analytic_account.py
> +            date = fields.Date.from_string(account.recurring_next_date)
Aquí sacaría el if para arriba
```
if account.recurring_invoices and account.recurring_next_date:
    date = fields.Date.from_string(account.recurring_next_date)
    year = date.year
    month = date.month
    day = '01'
    monthrange = calendar.monthrange(year, month)[1]
    if account.recurring_last_day:
        day = monthrange
    if account.recurring_the_day <= monthrange:
        day = account.recurring_the_day
    account.recurring_next_date = "{}-{}-{}".format(year, month, day)
```
De esta forma queda mucho más limpio, y consigues lo mismo. Por otro lado, no sería posible cargar este dato en un default o en algún onchange en vez de machacar el create?

2016-10-18 08:38 UTC, agaldona commented on account_analytic_analysis_recurring_day/models/account_analytic_account.py
> +                date = fields.Date.from_string(str(date))
esto no sería lo mismo que hacer `date=date` ??

2016-10-18 13:38 UTC, agaldona approved these changes

2016-10-18 13:38 UTC, merged