[ADD] purchase_requisition_purchase_price: Best purchase price in pur…
avanzosc/odoo-addons pull request #399
Opened 2017-02-23 08:45 UTC by alfredoavanzosc

…chase requisition.
De las líneas de compra asociadas a un purchase requisition, coger el precio mas bajo.

2017-02-23 10:40 UTC, alfredoavanzosc commented
@avanzosc/developers ...¿podéis validar este nuevo módulo?. Eskerrik asko.

2017-02-23 12:07 UTC, agaldona requested changes

2017-02-23 12:07 UTC, agaldona commented on purchase_requisition_purchase_price/i18n/es.po
> +msgstr "Usada cantidad parcial"
Cantidad parcial usada

2017-02-23 12:07 UTC, agaldona commented on purchase_requisition_purchase_price/i18n/es.po
> +msgstr "Usada cantidad total"
Cantidad total usada

2017-02-23 12:07 UTC, agaldona commented on purchase_requisition_purchase_price/models/purchase_requisition.py
> +    purchase_price = fields.Float(
No entiendo porque modificas este valor cada vez que hay un cambio en las líneas de compra utilizando las funciones de create, unlink y write de las lineas de compra. Si este campo se recalcula cada vez que hay una modificacion en líneas de compra y en los campos precio unidad y cantidad, ¿por que no pones este campo calculado en base a eso, y te olvidas de heredar funciones como write, create y unlink?

2017-02-23 12:07 UTC, oihane commented on purchase_requisition_purchase_price/models/purchase_order_line.py
> +    purchase_requisition_line_id = fields.Many2one(
requisition_line_id, no uses nombres tan largos, procura que sean claros y lo más cortos.

2017-02-23 12:08 UTC, oihane commented on purchase_requisition_purchase_price/models/purchase_requisition.py
> +    purchase_order_line_ids = fields.One2many(
purchase_line_id, más corto, y claro

2017-02-23 12:09 UTC, oihane commented on purchase_requisition_purchase_price/__openerp__.py
> +        'purchase_requisition_from_sale_order',
¿Porque esta dependencia si no haces nada con ventas?

2017-02-23 12:19 UTC, alfredoavanzosc commented on purchase_requisition_purchase_price/models/purchase_requisition.py
> +    purchase_price = fields.Float(
No puedo poner este campo calculado, porque me han solicitado que sea editable.

2017-02-23 12:20 UTC, oihane commented on purchase_requisition_purchase_price/models/purchase_order_line.py
> +        prequisition_lines = self.env['purchase.requisition.line']
prequisition_lines = self.mapped('purchase_requisition_line_id')

2017-02-23 12:26 UTC, Daniel-CA commented on purchase_requisition_purchase_price/models/purchase_requisition.py
> +    purchase_price = fields.Float(
Para que un campo calculado pueda ser editable hay que definir una función inversa con ```inverse=funcion_inversa```

2017-02-23 15:53 UTC, alfredoavanzosc commented
@avanzosc/developers .. realizadas las mejoras que me habéis dicho. ¿Revisáis por favor otra vez?. Eskerrik asko.

2017-02-23 16:03 UTC, agaldona commented on purchase_requisition_purchase_price/models/purchase_requisition.py
> +            line.unit_cost = line.total_cost / line.product_qty
Se que no es lo normal, pero basta que en un momento dado vacies el campo product_qty y este a 0 para que esto te de un traceback de Float division by Zero. Añade un control.

2017-02-24 07:13 UTC, alfredoavanzosc commented on purchase_requisition_purchase_price/models/purchase_requisition.py
> +            line.unit_cost = line.total_cost / line.product_qty
Arreglado el error detectado por @agaldona , y subido el módulo. Eskerrik asko.

2017-02-24 08:00 UTC, agaldona approved these changes
:+1:

2017-02-24 09:21 UTC, Daniel-CA commented
:+1:

2017-02-24 09:46 UTC, merged