[ADD]analytic_line_kind:adds a new Many2One field
avanzosc/odoo-addons pull request #577
Opened 2018-04-26 09:55 UTC by maiteesnal

adds a new Many2One field

2018-05-03 08:07 UTC, maiteesnal commented
@avanzosc/developers

2018-05-03 09:40 UTC, alfredoavanzosc commented
@maiteesnal ... solo un detalle en el nombre de una vista, el resto lo veo ok.

2018-05-03 11:44 UTC, alfredoavanzosc commented on analytic_line_kind/views/account_analytic_line_kind_view.xml
> +            <field name="name">account.analytic.line.kind.view</field>
la etiqueta name deberia ser "account.analytic.line.kind.tree.view", recuerda... igual que el ID, pero separados por puntos.

2018-05-03 12:04 UTC, oihane requested changes
Normalmente en todos los ficheros *.py ponemos la licencia que incluye el copyright (aunque no es obligatorio, te recomiendo hacerlo)
Además te falta incluir el fichero README.rst donde se pone la descripción del modulo.
Tienes un ejemplo en https://raw.githubusercontent.com/OCA/maintainer-tools/master/template/module/README.rst

2018-05-03 12:04 UTC, oihane commented on analytic_line_kind/__manifest__.py
> +    "name": "analytic line kind",
Pon `Analytic line classification`

2018-05-03 12:04 UTC, oihane commented on analytic_line_kind/__manifest__.py
> +    "category": "",
```python
   "category": "Accounting",
```

2018-05-03 12:04 UTC, oihane commented on analytic_line_kind/__manifest__.py
> +    'auto_install': False,
Tanto `demo` como `auto_install` no los pondría porque no son necesarios además para mi es más visual que no esté el `auto_install`

2018-05-03 12:04 UTC, oihane commented on analytic_line_kind/models/__init__.py
> +from . import account_analytic_line
Salto de línea al final, si te fijas cuando subas el github te lo indica que falta

2018-05-03 12:04 UTC, oihane commented on analytic_line_kind/models/account_analytic_line.py
> +    analytic_line_kind_id = fields.Many2one(
Para facilitar las cosas, si se puede al menos, los nombres de los campos hay que tratar de que sean cortos. En este caso podrías poner `kind_id`
Incluyelo además en la vista de listado y pon búsqueda y agrupación por el mismo.

2018-05-03 12:04 UTC, oihane commented on analytic_line_kind/views/account_analytic_line_kind_view.xml
> +<openerp>
la etiqueta en v11 es `<odoo>`

2018-05-03 12:04 UTC, oihane commented on analytic_line_kind/models/account_analytic_line.py
> +    name = fields.Char(string="Account analytic line kind", required=True)
Ponle `translate=True` para que se le pueda traducir el nombre al tipo

2018-05-04 09:02 UTC, maiteesnal commented
Ya he echo todos los cambios sugeridos, si podeis echarle un último vistazo...
Gracias :D
@alfredoavanzosc @oihane @Daniel-CA @mikelarre

2018-05-04 09:16 UTC, oihane submitted a review, later dismissed

2018-05-04 09:16 UTC, oihane commented on analytic_line_kind/README.rst
> +====================================
```
============================
Analytic line classification
============================
```

Las líneas de **=** tiene que tener la misma longitud de caracteres que el titulo del modulo.

2018-05-04 09:16 UTC, oihane commented on analytic_line_kind/README.rst
> +Installation
Si no tiene nada de especial, no lo pongas

2018-05-04 09:16 UTC, oihane commented on analytic_line_kind/README.rst
> +Configuration
Lo mismo, no tiene porque contener todos los puntos

2018-05-04 09:16 UTC, oihane commented on analytic_line_kind/README.rst
> +<https://github.com/OCA/{project_repo}/issues>`_. In case of trouble, please
Tienes que modificar este enlace para que coincida con el que corresponde,
en este caso:
```
<https://github.com/avanzosc/odoo-addons/issues>
```

2018-05-04 09:16 UTC, oihane commented on analytic_line_kind/README.rst
> +Images
No tiene ninguna imagen y menos de OCA, quita está parte

2018-05-04 11:01 UTC, Daniel-CA submitted a review, later dismissed

2018-05-04 11:45 UTC, oihane commented on analytic_line_kind/README.rst
> +============
Elimina la parte de INSTALLATION pero manten la descripcion del modulo

2018-05-04 12:16 UTC, anajuaristi commented
Está mal. Por favor, poned en foco en las revisiones. 
El campo NO SE VE en el tree porque no ha metido herencia y en filtros, tampoco se extiende.

:-1:

2018-05-07 14:03 UTC, Daniel-CA commented on analytic_line_kind/views/account_analytic_line_view.xml
> +                <tree string="Analytic Entries">
La clave ```tree``` sobra.

2018-05-07 14:03 UTC, Daniel-CA commented on analytic_line_kind/views/account_analytic_line_view.xml
>              <field name="arch" type="xml">
La clave ```search``` sobra.

2018-05-07 15:42 UTC, merged