[ADD]  website_blog_characterization: With this module you can charact…
avanzosc/odoo-addons pull request #607
Opened 2018-07-11 09:27 UTC by gotzonavanzosc

…erize different parameters for blog entries.

2018-07-11 09:33 UTC, gotzonavanzosc commented
@avanzosc/developers review please

2018-07-11 09:36 UTC, gotzonavanzosc commented
@alfredoavanzosc , @oihane , @Daniel-CA , @mikelarre .... review please

2018-07-11 09:48 UTC, oihane commented on partner_characterization_blog/models/blog_post.py
> +    area_ids = fields.Many2many(
Revisa los m2m. No puedes usar las mismas *relation* que usa el partner y menos usando la misma columna

2018-07-11 09:51 UTC, oihane requested changes
El modulo debería de ser website_blog_characterization y debería depender de base_characterization (que es el modulo que crea los objetos) y de website_blog

2018-07-11 10:15 UTC, oihane commented
Otra cosa, que no es necesaria que cambies para este PR
Deberás hacer: 
```
git config --global user.name "Gotzon Imaz"
git config --global user.email "correo.usado@github.com"
```
Poniendo el correo del usuario @gotzonavanzosc para que los commits no aparezcan como maiteesnal, por cierto me dijo Ana que ya teniais usuario de github, no tenias porque haber creado este otro.

2018-07-11 10:18 UTC, oihane submitted a review, later dismissed

2018-07-11 10:18 UTC, oihane commented on website_blog_characterization/__manifest__.py
> +    "name": "Partner Characterization Blog",
Cambia el nombre para que coincida con el del README

2018-07-11 10:18 UTC, oihane commented on website_blog_characterization/__manifest__.py
> +    "category": "Customers, Vendors, Partners,...",
Usa la categoria de *website_blog*  **Website**

2018-07-11 10:18 UTC, oihane commented on website_blog_characterization/__manifest__.py
> +        "partner_characterization",
Debes cambiar la dependencia.

2018-07-11 11:04 UTC, gotzonavanzosc commented
Ohiane, the changes have been made. Thank you!

2018-07-11 11:16 UTC, gotzonavanzosc commented
@oihane, the changes have been made. Thank you!

2018-07-20 10:56 UTC, alfredoavanzosc approved these changes
:+1:

2018-07-20 11:23 UTC, Daniel-CA requested changes

2018-07-20 11:23 UTC, Daniel-CA commented on website_blog_characterization/views/blog_post_view.xml
> +<?xml version="1.0"?>
```<?xml version="1.0" encoding="UTF-8"?>```

2018-07-20 11:59 UTC, gotzonavanzosc commented
@avanzosc/developers review please

2018-07-24 09:11 UTC, Daniel-CA reviewed
LGTM :+1:

2018-07-24 09:16 UTC, Daniel-CA approved these changes

2018-07-24 09:17 UTC, merged