[ADD] mail_template_characterization: This module adds new fields to …
avanzosc/odoo-addons pull request #608
Opened 2018-07-11 11:03 UTC by eideravanzosc

…the email template.

2018-07-11 11:24 UTC, eideravanzosc commented
@alfredoavanzosc , @oihane , @Daniel-CA , @mikelarre 
...review, please...

2018-07-11 13:43 UTC, oihane commented on mail_template_characterization/models/mail_template.py
> +# -*- coding: utf-8 -*-
En v11 como se usa Python3 no se pone el coding

2018-07-11 13:43 UTC, oihane commented on mail_template_characterization/views/mail_template_views.xml
> +    <data>
En v11 esto no es necesario

2018-07-12 07:41 UTC, eideravanzosc commented
@oihane 

Las mejoras solicitadas han sido realizadas

2018-07-12 08:25 UTC, Daniel-CA commented on mail_template_characterization/views/mail_template_views.xml
> +</odoo>
Falta un espacio al final del xml

2018-07-12 09:00 UTC, eideravanzosc commented
@Daniel-CA 

He realizado el cambio solicitado

2018-07-12 13:44 UTC, oihane commented on partner_documentation/tests/test_partner_documentation.py
> +        line = self.partner_customer.document_lines[0]
Este cambio de donde sale, ni siquiera pertenece al mismo modulo

2018-07-13 06:44 UTC, Daniel-CA commented on partner_documentation/tests/test_partner_documentation.py
> +        line = self.partner_customer.document_lines[0]
Esos cambios los ha metido por que el Travis le daba rojo. Cuando hiciste los cambios en el partner_documentation hiciste el merge en rojo y faltaban algunos test.
Debería hacerse en otro PR pero bueno, por mi parte no hay problema.
:+1:

2018-07-13 06:44 UTC, Daniel-CA approved these changes

2018-07-13 07:04 UTC, Daniel-CA commented on partner_documentation/tests/test_partner_documentation.py
> +        res = self.partner_customer.show_attachments()
res = self.partner_customer.show_attachment()

2018-07-13 07:05 UTC, Daniel-CA requested changes
Cambia la linea que te comento a ver si te pasa el Travis

2018-07-13 07:13 UTC, Daniel-CA commented on partner_documentation/tests/test_partner_documentation.py
> +        self.assertEqual(res, True, 'Error, attacment 1')
Attachment

2018-07-13 07:13 UTC, Daniel-CA commented on partner_documentation/tests/test_partner_documentation.py
> +        self.assertEqual(res, True, 'Error, attacment 2')
Attachment

2018-07-13 07:45 UTC, oihane commented on mail_template_characterization/views/mail_template_views.xml
> +<?xml version="1.0"?>
Añade lo de UTF-8, solo es en el caso de los py cuando no se pone.

2018-07-13 07:46 UTC, oihane commented on mail_template_characterization/models/mail_template.py
> +# Part of Odoo. See LICENSE file for full copyright and licensing details.
Copia lo mismo que en el resto de py

2018-07-13 07:49 UTC, oihane commented on partner_documentation/tests/test_partner_documentation.py
> +        self.partner_customer.document_lines[0].document_attachment.unlink()
No añadas cambios de otro modulo no relacionado en este PR.

2018-07-13 08:15 UTC, eideravanzosc commented on partner_documentation/tests/test_partner_documentation.py
> +        self.partner_customer.document_lines[0].document_attachment.unlink()
@oihane
Es para arreglar el test de partner_documentation, porque si no modulo no pasaba coveralls.

2018-07-13 08:20 UTC, oihane commented on partner_documentation/tests/test_partner_documentation.py
> +        self.partner_customer.document_lines[0].document_attachment.unlink()
El coveralls no es bloqueante, por lo que si el modulo está al 100% es suficiente, en el caso de tu modulo
![image](https://user-images.githubusercontent.com/2323616/42680763-390f802c-8686-11e8-9897-ee95a338a695.png)
es correcto, y es más limpio que se proponga el cambio en otro PR.

2018-07-13 08:25 UTC, eideravanzosc commented on partner_documentation/tests/test_partner_documentation.py
> +        self.assertEqual(res, True, 'Error, attacment 1')
@Daniel-CA
Eskerrik asko. Test arreglado

2018-07-18 08:05 UTC, oihane requested changes

2018-07-18 08:05 UTC, oihane commented on mail_template_characterization/__manifest__.py
> +
Elimina está línea vacia

2018-07-18 08:21 UTC, eideravanzosc commented
@oihane 

He hecho el cambio solicitado

2018-07-18 08:25 UTC, Daniel-CA approved these changes
LGTM  :+1:

2018-07-24 09:06 UTC, oihane approved these changes

2018-07-24 09:07 UTC, merged