[IMP] product_variant_extra_price: In general settings there is a new…
avanzosc/odoo-addons pull request #613
Opened 2018-07-13 10:46 UTC by gotzonavanzosc

… field called "Prices in products" to define

how many prices show in product form.

2018-07-13 11:01 UTC, oihane commented on product_variant_extra_price/README.rst
> +* Gotzon Imaz <gotzonimaz@avanzosc.es>
NO PUEDES QUITAR A @alfredoavanzosc

2018-07-13 11:04 UTC, oihane commented
TRAVIS:
```
product_variant_extra_price/models/base_config_settings.py:8:43: E999 SyntaxError: invalid syntax
product_variant_extra_price/models/product_product.py:4:1: F401 'openerp.api' imported but unused
```

2018-07-13 11:34 UTC, oihane commented on product_variant_extra_price/__openerp__.py
> +        "Gotzon Imaz <gotzonimaz@avanzosc.es>",
Aquí también debes respetarlo

2018-07-13 11:35 UTC, oihane commented on product_variant_extra_price/models/base_config_settings.py
> +# Copyright 2017 Alfredo de la Fuente - AvanzOSC
Si lo estas creando tú, lo normal es que sea tu nombre el que aparece, junto con el año actual.

2018-07-13 11:37 UTC, oihane commented on product_variant_extra_price/models/base_config_settings.py
> +from openerp import fields, models, api
https://github.com/OCA/maintainer-tools/blob/master/CONTRIBUTING.md#imports

OCA dice `# alphabetically ordered`

2018-07-13 11:38 UTC, oihane commented on product_variant_extra_price/models/base_config_settings.py
> +        [('2', '2'), ('3', '3'),
pon `selection=[` no es requerido pero en OCA lo piden y así te iras acostumbrando

2018-07-17 07:26 UTC, oihane commented
TRAVIS:
```
product_variant_extra_price/models/base_config_settings.py:4:40: W291 trailing whitespace
product_variant_extra_price/models/base_config_settings.py:14:1: W293 blank line contains whitespace
```

```

2018-07-16 12:09:48,659 6363 INFO openerp_test openerp.modules.module: openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price running tests.
2018-07-16 12:09:48,659 6363 INFO openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: test_product_variant_extra_price_1 (openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price.TestProductVariantExtraPrice)
2018-07-16 12:09:48,985 6363 ERROR openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: FAIL
2018-07-16 12:09:48,986 6363 INFO openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: test_product_variant_extra_price_2 (openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price.TestProductVariantExtraPrice)
2018-07-16 12:09:49,272 6363 INFO openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: ======================================================================
2018-07-16 12:09:49,272 6363 ERROR openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: FAIL: test_product_variant_extra_price_1 (openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price.TestProductVariantExtraPrice)
2018-07-16 12:09:49,273 6363 ERROR openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: Traceback (most recent call last):
2018-07-16 12:09:49,273 6363 ERROR openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: `   File "/home/travis/build/avanzosc/odoo-addons/product_variant_extra_price/tests/test_product_variant_extra_price.py", line 22, in test_product_variant_extra_price_1
2018-07-16 12:09:49,273 6363 ERROR openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: `     'Bad value in product')
2018-07-16 12:09:49,273 6363 ERROR openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: ` AssertionError: False != '2' : Bad value in product
2018-07-16 12:09:49,273 6363 INFO openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: Ran 2 tests in 0.614s
2018-07-16 12:09:49,273 6363 ERROR openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price: FAILED
2018-07-16 12:09:49,273 6363 INFO openerp_test openerp.addons.product_variant_extra_price.tests.test_product_variant_extra_price:  (failures=1)
2018-07-16 12:09:49,273 6363 ERROR openerp_test openerp.modules.module: Module product_variant_extra_price: 1 failures, 0 errors
```

2018-07-18 07:57 UTC, oihane submitted a review, later dismissed
Cambios pendientes

2018-07-20 11:00 UTC, alfredoavanzosc approved these changes
:+1:

2018-07-24 10:34 UTC, oihane requested changes

2018-07-24 10:34 UTC, oihane commented on product_variant_extra_price/models/__init__.py
> +# Copyright 2018 Gotzon Imaz - AvanzOSC
No lo cambies

2018-07-24 10:34 UTC, oihane commented on product_variant_extra_price/models/base_config_settings.py
> +
Sobra

2018-07-24 10:34 UTC, oihane commented on product_variant_extra_price/models/product_product.py
> +# Copyright 2017 Gotzon Imaz - AvanzOSC
No lo cambies

2018-07-24 10:34 UTC, oihane commented on product_variant_extra_price/tests/test_product_variant_extra_price.py
> +        self.product._compute_number_price_field()
Si lees el campo esto no se debe ejecutar automaticamente. No es necesario llamarlo.

2018-07-24 10:34 UTC, oihane commented on product_variant_extra_price/models/product_product.py
> +        [('2', '2'), ('3', '3'),
Ponle el `selection=`

2018-07-24 11:59 UTC, gotzonavanzosc commented
@oihane changes made

2018-07-24 13:29 UTC, oihane approved these changes

2018-07-24 13:29 UTC, merged