[ADD]<sales_team_utilities>: This application makes visible the "team…
avanzosc/odoo-addons pull request #615
Opened 2018-07-16 08:45 UTC by eideravanzosc

…_id" field in res.partner tree, form and filter views

review, please

2018-07-18 07:58 UTC, oihane requested changes

2018-07-18 07:58 UTC, oihane commented on sales_team_utilities/__manifest__.py
> +
Línea de más

2018-07-18 07:58 UTC, oihane commented on sales_team_utilities/__manifest__.py
> +        'depends': ['sales_team',
tabulacion que sobra

2018-07-18 08:14 UTC, eideravanzosc commented
@oihane  
He realizado los cambios

2018-07-20 10:57 UTC, eideravanzosc commented
@oihane , @Daniel-CA , @alfredoavanzosc , @mikelarre 

review...

2018-07-20 11:13 UTC, Daniel-CA reviewed
Si es un módulo de ventas debería ir a la rama sale-addons.

2018-07-24 09:08 UTC, oihane commented
Como dice @Daniel-CA este modulo debe de proponerse a la rama sale-addons, cierro el PR.

2018-07-24 09:08 UTC, closed without merging