[MOD] stock_picking_service_sale: test fix
avanzosc/odoo-addons pull request #716
Opened 2019-04-16 10:58 UTC by mikelarre

2019-04-17 06:34 UTC, alfredoavanzosc approved these changes
:+1:

2019-04-23 11:05 UTC, oihane requested changes
Revisar que valor tienen esos picking, porque deberian de ser para facturar por la configuración que tiene el pedido de venta.

2019-04-23 11:05 UTC, oihane commented on stock_picking_service_sale/tests/test_stock_picking_service_sale.py
> +        self.picking.invoice_state = "2binvoiced"
Si el 'order_policy' del pedido de venta es 'picking' este campo tiene ese valor, si no es así hay alguna otra cosa que impacta.

2019-04-23 11:05 UTC, oihane commented on stock_picking_service_sale/__openerp__.py
> +    "version": "8.0.1.0.1",
Si lo que se modifica es el test, no es necesario incrementar la versión.

2019-07-26 11:14 UTC, merged