[ADD] fleet_route: This module create the new objects 'Itinerary' and…
avanzosc/odoo-addons pull request #737
Opened 2019-06-13 07:00 UTC by OihanaLarranaga

… 'Route'.

2019-06-13 07:00 UTC, OihanaLarranaga commented
Realizadas las mejoras solicitadas por @oihane . Eskerrik asko.

2019-06-13 07:35 UTC, oihane requested changes
Lo de copyright es parte de la licencia, no solo la línea de que establece el tipo de licencia.

Las pautas a seguir que marca **OCA** las tienes en https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst

2019-06-13 07:35 UTC, oihane commented on fleet_route/__init__.py
> +from . import models
No es necesario añadir las licencias porque no tiene código que licenciar.

2019-06-13 07:35 UTC, oihane commented on fleet_route/__manifest__.py
> +        "resource"
Mejor finalizar con una coma, por si alguien le añade más dependencias está línea no se marcará como modificada.

2019-06-13 07:35 UTC, oihane commented on fleet_route/__manifest__.py
> +        "views/fleet_route_view.xml"
igual que la anterior, con `,` al final

2019-06-13 07:35 UTC, oihane commented on fleet_route/data/fleet_route_data.xml
> +</odoo>
Falta un salto de línea

2019-06-13 07:35 UTC, oihane commented on fleet_route/models/__init__.py
> +from . import fleet
Eliminar la licencia.

2019-06-13 07:35 UTC, oihane commented on fleet_route/views/fleet_route_view.xml
> +                <form string="Itinerary">
Creo que esto es un fallo del copy / paste, debería de ser Route, aunque tampoco es obligatorio o necesario poner ese texto.

2019-06-13 07:35 UTC, oihane commented on fleet_route/views/fleet_route_view.xml
> +
elimina la línea vacia

2019-06-13 07:35 UTC, oihane commented on fleet_route/views/base_itinerary_view.xml
> +</odoo>
Revisa el formateo, para que no tenga identaciones de más tambien se hace de la siguiente manera
```xml
    <menuitem id="fleet_itinerary2_menuitem"
              action="action_fleet_itinerary"
              parent="fleet_itinerary_menuitem" />
```
**action** queda a la altura de **id** y lo mismo con **parent**

2019-06-13 10:43 UTC, OihanaLarranaga commented
Realizadas las mejoras solicitadas por @oihane . Eskerrik asko.

2019-06-13 10:59 UTC, oihane requested changes

2019-06-13 10:59 UTC, oihane commented on fleet_route/models/fleet.py
> +    @api.multi
Las funciones compute se ponen despues de las declaraciones de los campos. dado que a la hora de llamar a dichas funciones se declaran de la siguiente manera, `compute='_compute_nombrecampo'`

Las funciones que se ponen antes de los campos suelen ser aquellas que te obliga la misma definición, que normalmente son los `_default` y los `_selection`

2019-06-13 10:59 UTC, oihane commented on fleet_route/models/fleet.py
> +            route.manager_phone_mobile = u"{}/{}".format(
en v12 no es necesario poner `u""` que corresponde a unicode porque python3 lo tiene por defecto.

2019-06-13 10:59 UTC, oihane commented on fleet_route/models/fleet.py
> +    @api.multi
Dado que estos campos van a ir en el tree, deben ser persistentes en base de datos osea `store=True` y por lo tanto deberán tener definido el `@api.depends` con esto no necesitan tener el `@api.multi`

```python
@api.depends('manager_id', 'manager_id.work_phone', 'manager_id.mobile_phone')
def _compute_manager_phone_mobile(self):
```

Como puedes observar se ponen en el depends los **campos** que luego se usan en la función

2019-06-14 06:47 UTC, OihanaLarranaga commented
Realizadas las mejoras solicitadas por @oihane

2019-06-17 12:39 UTC, OihanaLarranaga commented on fleet_route/models/fleet.py
> +    @api.multi
Realizadas las mejoras solicitadas por @oihane , eskerrik asko.

2019-06-18 08:36 UTC, closed without merging