[ADD] stock_utilities: Show stock deno in stock pickings.
avanzosc/odoo-addons pull request #804
Opened 2019-12-13 08:09 UTC by alfredoavanzosc

2019-12-13 08:38 UTC, alfredoavanzosc commented
@avanzosc/developers ... review please

2019-12-13 13:21 UTC, mikelarre approved these changes

2019-12-16 11:23 UTC, oihane submitted a review, later dismissed
El modulo debería de ser stock_usability (para evitar los nombres en plural) y la opción de cambiar lo que se muestra configurable por permisos.

2019-12-17 08:33 UTC, oihane submitted a review, later dismissed
*por revisar*

2019-12-17 08:33 UTC, oihane commented on stock_usability/__init__.py
> +from . import models
En aquellos ficheros donde lo único que se hace es importar no se pone la parte de la licencia y el copyright

2019-12-17 08:34 UTC, oihane commented on stock_usability/models/res_config_settings.py
> +        config_parameter='stock_usuability.show_stock_move_deno')
misstyped

2019-12-17 09:16 UTC, alfredoavanzosc commented on stock_usability/models/res_config_settings.py
> +        config_parameter='stock_usuability.show_stock_move_deno')
@oihane ... no se que me quieres decir

2019-12-17 10:18 UTC, oihane requested changes
*sin revisar*

2019-12-17 10:54 UTC, oihane submitted a review, later dismissed

2019-12-17 10:54 UTC, oihane commented on stock_usability/i18n/es.po
> +msgstr "Movimietos de Almacén sin paquete"
misstype

2019-12-17 10:54 UTC, oihane commented on stock_usability/models/res_config_settings.py
> +        config_parameter='stock_usability.show_stock_move_deno')
Es mucho más fácil si lo que haces es considerarlo como un grupo y aplicar el grupo a la vista

2019-12-17 10:54 UTC, oihane commented on stock_usability/views/stock_picking_view.xml
> +                    <field name="move_ids_without_package2" attrs="{'readonly': ['|', '&amp;', ('show_operations', '=', True), '|', ('is_locked', '=', True), ('state', '=', 'done'), '&amp;', ('state'
Y que pasa en el caso de que su usen paquetes? porque hay una vista de operaciones detalladas que no estas teniendo en cuenta a la hora de mostrar la descripción.

2019-12-17 14:38 UTC, alfredoavanzosc commented on stock_usability/i18n/es.po
> +msgstr "Movimietos de Almacén sin paquete"
Arreglado. Eskerrik asko @oihane

2019-12-17 16:13 UTC, oihane submitted a review, later dismissed
Pero no puedes ponerlo por configuración, mira en [analytic-usability](https://github.com/avanzosc/odoo-addons/blob/12.0/analytic_usability/models/res_config.py)

2019-12-18 08:46 UTC, oihane commented on stock_usability/__init__.py
> +from . import models
falta salto de línea

2019-12-18 09:34 UTC, alfredoavanzosc commented on stock_usability/__init__.py
> +from . import models
Puesto el salto de línea, eskerrik asko @oihane

2019-12-19 08:55 UTC, oihane submitted a review, later dismissed

2019-12-19 08:55 UTC, oihane commented on stock_usability/views/res_config_view.xml
> +            <xpath expr="//div[@class='app_settings_block']" position="inside" >
Instalado en demo, el ajuste aparece en dentro de los ajustes de CRM, cuando debería de estar dentro de los de inventario.
![image](https://user-images.githubusercontent.com/2323616/71158325-07ab2a80-2244-11ea-8978-f2af6c1aea14.png)

2019-12-23 11:42 UTC, Daniel-CA approved these changes

2019-12-23 11:42 UTC, merged