[ADD] Education group mail list
avanzosc/odoo-addons pull request #851
Opened 2020-04-20 14:16 UTC by adrianrevilla009

2020-05-06 12:54 UTC, oihane requested changes
Revisa el TRAVIS, al menos eso debe de estar en verde para fusionar.

![image](https://user-images.githubusercontent.com/2323616/81179103-7e558400-8fa9-11ea-9e33-3c943842d8dc.png)

2020-05-12 13:20 UTC, oihane submitted a review, later dismissed
Elimina la parte del informe de los progenitores, lo he añadido en el modulo contacts_school_education

2020-06-08 18:57 UTC, anajuaristi approved these changes

2020-06-09 05:46 UTC, alfredoavanzosc approved these changes
:+1:

2020-06-09 07:31 UTC, merged