[ADD] website_stock
avanzosc/odoo-addons pull request #869
Opened 2020-05-08 11:47 UTC by adrianrevilla009

Añadir modulo website_stock de HLC

2020-05-12 06:53 UTC, adrianrevilla009 commented
Subida de módulos para que sean probados.
Errores del travis por completar.

2020-05-15 11:36 UTC, adrianrevilla009 commented
Genericidad para la función de filtrado utilizada en todos los módulos.

2020-05-18 11:42 UTC, adrianrevilla009 commented
[FIX] Modificar espacios para que pase el travis.

2020-05-20 07:56 UTC, adrianrevilla009 commented
Añadida paginación en el modulo.

2020-05-27 07:03 UTC, Daniel-CA commented
Falta archivo readme explicando que hace el módulo.

2020-05-29 10:12 UTC, adrianrevilla009 commented
Added README file.

2020-06-05 08:34 UTC, Daniel-CA commented
Tienes que arreglar los errores de Flake8, para poder fusionar el módulo en la rama principal.

2020-06-30 09:37 UTC, adrianrevilla009 commented
Reclamación CLM8211.
Añadida firma e impresión al módulo web de albaranes.

2020-07-08 12:03 UTC, Daniel-CA approved these changes

2020-07-09 14:48 UTC, Daniel-CA commented
@avanzosc/developers review please

2020-07-10 10:53 UTC, adrianrevilla009 commented
Formateo de vistas.

2020-07-14 07:16 UTC, alfredoavanzosc approved these changes
:+1:

2020-07-14 07:20 UTC, Daniel-CA requested changes

2020-07-14 07:20 UTC, Daniel-CA commented on website_stock/models/__init__.py
> +from . import stock_picking
Falta un return

2020-07-14 07:20 UTC, Daniel-CA commented on website_stock/models/stock_picking.py
> +    _name = "stock.picking"
para heredar esta clase solo tienes que hacer _inherit = 'stock.picking"

2020-07-14 07:20 UTC, Daniel-CA commented on website_stock/tests/__init__.py
> +from . import test_website_stock
falta salto de linea

2020-07-14 09:49 UTC, oihane commented on website_stock/models/stock_picking.py
> +    _name = "stock.picking"
Pero lo que quiere hacer es extender el `inherit` para hacer que tenga chatter
Yo creo que es correcto y hay un ejemplo en https://github.com/OCA/currency/blob/12.0/currency_rate_update/models/res_currency_rate.py#L8

2020-07-14 09:52 UTC, adrianrevilla009 commented
modificado @avanzosc/developers

2020-07-14 09:52 UTC, oihane commented on website_stock/models/stock_picking.py
> +    _name = "stock.picking"
Hecha la consulta, la respuesta es:
**al heredar de múltiples modelos, hay que decir en cuál "queda" el resultado**

2020-07-14 10:05 UTC, Daniel-CA approved these changes

2020-07-14 11:20 UTC, merged