[ADD] website_base_filter
avanzosc/odoo-addons pull request #871
Opened 2020-05-13 13:51 UTC by adrianrevilla009

Funciones comunes de los modulos web.

2020-05-15 11:33 UTC, adrianrevilla009 commented
Genericidad para la función de filtrado utilizada en todos los módulos.

2020-05-18 11:38 UTC, adrianrevilla009 commented
[FIX] Modificar espacios para que pase el travis.

2020-05-19 14:02 UTC, oihane requested changes

2020-05-19 14:02 UTC, oihane commented on website_base_filter/static/src/css/style.css
> +}
Falta un salto de línea

2020-05-19 14:02 UTC, oihane commented on website_base_filter/static/src/js/help_functions.js
> +
Sobran saltos de línea

2020-05-19 14:02 UTC, oihane commented on website_base_filter/views/website_base_filter_template.xml
> +</odoo>
Falta salto de línea

2020-05-29 10:11 UTC, adrianrevilla009 commented
Added README file.

2020-06-08 12:41 UTC, adrianrevilla009 commented
cambiado domain para la obtención de datos

2020-06-08 15:21 UTC, oihane commented
PEP8
```
website_base_filter/controllers/generic_functions.py:2:1: F401 'odoo.SUPERUSER_ID' imported but unused
website_base_filter/controllers/generic_functions.py:2:1: F401 'odoo._' imported but unused
website_base_filter/controllers/generic_functions.py:2:1: F401 'odoo.http' imported but unused
website_base_filter/controllers/generic_functions.py:4:1: F401 'odoo.addons.portal.controllers.portal.pager as portal_pager' imported but unused
website_base_filter/controllers/generic_functions.py:4:80: E501 line too long (87 > 79 characters)
website_base_filter/controllers/generic_functions.py:263:80: E501 line too long (81 > 79 characters)
```

PYLINT
```
website_base_filter/static/src/js/generic_functions.js:34: [W7903(javascript-lint), ] Parsing error: Unexpected token i [Error]
website_base_filter/views/website_base_filter_template.xml:1: [W7908(missing-newline-extrafiles), ]  Missing newline
website_base_filter/README.rst:10: [W7910(wrong-tabs-instead-of-spaces), ]  Use wrong tabs indentation instead of four spaces
```

2020-06-09 08:22 UTC, oihane commented on website_base_filter/controllers/__init__.py
> +from . import generic_functions
falta salto de línea

2020-06-09 13:48 UTC, Daniel-CA commented
Te falta añadir los test del controler, mira a ver si te vale este de ejemplo:
https://github.com/OCA/website/blob/12.0/website_adv_image_optimization/tests/test_controller.py

2020-06-16 09:25 UTC, Daniel-CA approved these changes

2020-06-16 09:25 UTC, oihane approved these changes

2020-06-16 09:26 UTC, merged