[ADD] sale_partner_company
avanzosc/odoo-addons pull request #875
Opened 2020-05-20 13:53 UTC by adrianrevilla009

Módulo para poder vender sólo a los clientes "compañía" -> Pedidos de venta

2020-05-21 05:51 UTC, alfredoavanzosc commented on sale_partner_company/views/sale_partner_company_view.xml
> +</odoo>
Te falta salto de línea al final.

2020-05-21 05:52 UTC, alfredoavanzosc commented
Falta el fichero README.rst

2020-05-21 07:06 UTC, adrianrevilla009 commented
Añadido fichero README.

2020-05-21 17:07 UTC, oihane requested changes

2020-05-21 17:07 UTC, oihane commented on sale_partner_company/views/sale_partner_company_view.xml
> +   <xpath expr="//field[@name='partner_id']" position="attributes">
Usa 4 espacios para simular los tabuladores
y en vez de xpath, en este caso
```html
<field name="partner_id" position="attributes">
```

2020-05-21 17:07 UTC, oihane commented on sale_partner_company/__manifest__.py
> +    'summary': '''Sale Partner Company''',
Si vas a copiar el NOMBRE del modulo, sobra

2020-05-21 17:07 UTC, oihane commented on sale_partner_company/__manifest__.py
> +        "sale_management",
Es suficiente con que dependa de "sale", ya que es la vista que modificas

2020-05-26 15:58 UTC, oihane approved these changes

2020-05-26 16:03 UTC, merged