[ADD] fleet_route_reports
avanzosc/odoo-addons pull request #895
Opened 2020-06-19 08:52 UTC by adrianrevilla009

2020-06-19 08:59 UTC, adrianrevilla009 commented
Reclamación CLM8172.
Listado / Informe de Rutas de Autobuses

2020-06-24 10:02 UTC, oihane commented
```
Error:
Odoo Server Error

Traceback (most recent call last):
 File "/opt/odoo/v12/github/oca/OCB/odoo/tools/safe_eval.py", line 350, in safe_eval
   return unsafe_eval(c, globals_dict, locals_dict)
 File "", line 1, in <module>
 File "/opt/odoo/v12/fleet_route_reports/models/fleet_route.py", line 21, in _get_report_base_filename
   return self.name
AttributeError: 'fleet.route' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
 File "/opt/odoo/v12/community/core/addons/web/controllers/main.py", line 1688, in report_download
   report_name = safe_eval(report.print_report_name, {'object': obj, 'time': time})
 File "/opt/odoo/v12/github/oca/OCB/odoo/tools/safe_eval.py", line 373, in safe_eval
   pycompat.reraise(ValueError, ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr)), exc_info[2])
 File "/opt/odoo/v12/github/oca/OCB/odoo/tools/pycompat.py", line 86, in reraise
   raise value.with_traceback(tb)
 File "/opt/odoo/v12/github/oca/OCB/odoo/tools/safe_eval.py", line 350, in safe_eval
   return unsafe_eval(c, globals_dict, locals_dict)
 File "", line 1, in <module>
 File "/opt/odoo/v12/fleet_route_reports/models/fleet_route.py", line 21, in _get_report_base_filename
   return self.name
ValueError: <class 'AttributeError'>: "'fleet.route' object has no attribute 'name'" while evaluating
'(object._get_report_base_filename())'
```

Da este error al intentar imprimir

2020-07-08 08:16 UTC, anajuaristi commented on fleet_route_reports/static/src/css/style.css
> +* {
Los informes no tienen CSS propio. Este sobraría. 
Si modificas un formato de un único informe, lo estás "sacando" de la imagen corporatíva de la compañía. Si el cliente pide un cambio en formato CSS debería ser general. Yo este lo quitaba directamente.

2020-07-08 08:16 UTC, anajuaristi commented on fleet_route_reports/views/fleet_route_issue_report_view.xml
> +  <t t-call="web.html_container">
Las indentaciones tienen que ser de 4 caracteres. No de un único caracter ya que hace poco legible el informe

2020-07-08 08:16 UTC, anajuaristi commented on fleet_route_reports/views/fleet_route_issue_report_view.xml
> +      <b>
Cuando se trate de que puedes poner el tag de apertura y el de cierre en una única línea, hazlo así ya que hace el informe muchísimo más legible y le quitas 2/3 de líneas
```html
<td class="text-left"><span t-field="issue.high_stop_id.display_name" /></td>
<td class="text-left"><span t-field="issue.high_stop_direction" /> </td>
```
o
```html
<b> Route:  <span t-field="doc.name_id.name" /> </b>
<br />
<b>  Shift: <t t-if="doc.abbreviation"> <span t-field="doc.abbreviation" /> </t>
                  <t t-if="doc.abbreviation and doc.direction">  - </t>
```

2020-07-08 10:11 UTC, adrianrevilla009 commented on fleet_route_reports/views/fleet_route_issue_report_view.xml
> +      <b>
Toda esta indentación se realiza con el formateador automático de Eclipse.
Ahora lo cambio.

2020-07-08 10:22 UTC, oihane commented on fleet_route_reports/models/fleet_route.py
> +    def _get_route_passenger_high_stop_route_issues(self, student_id,
Puedes hacer una sola
```
@api.multi
def _get_route_passenger_issues(self, student_id, type):
    cond = [('student_id', '=', student_id)]
    if type == "high":
          expression.And(("high_stop_route_id", "=" self.id), cond)
```

Igual no está correcto del todo, y además lo añadiría en el res.partner no en el fleet.route. además tienes que tener el type en cuenta

2020-07-08 11:10 UTC, adrianrevilla009 commented on fleet_route_reports/models/fleet_route.py
> +    def _get_route_passenger_high_stop_route_issues(self, student_id,
Modificadas las funciones.
Modificados los test.
Modificado el formato de los xml.
Lo de mover las funciones a res.partner no puedo hacerlo, ya que se les llama desde el objeto fleet.route del report.

2020-07-08 11:42 UTC, oihane submitted a review, later dismissed
Te falta el `__init__.py` en la carpeta TESTs

2020-07-09 09:59 UTC, adrianrevilla009 commented
Modificados los test para que concuerden con un pequeño cambio que he tenido que realizar en el modelo fleet.route.support, en el módulo que he resubido llamado fleet_route_support.

2020-07-10 11:03 UTC, adrianrevilla009 commented
Formateo de vistas.

2020-08-25 08:41 UTC, adrianrevilla009 commented
Modificado los test a consecuencia de los cambios realizados en el módelo fleet.route.support.
@avanzosc/developers

2020-09-03 08:24 UTC, adrianrevilla009 commented
Eliminados test.
Refactorizado el código python.
Unificadas las tablas en una ordenada por tipo.
@avanzosc/developers

2020-09-04 06:05 UTC, adrianrevilla009 commented
Sustituido el código del informe de pasajeros por el nuevo.

2020-09-04 09:15 UTC, anajuaristi approved these changes

2020-09-04 09:16 UTC, Daniel-CA approved these changes

2020-09-04 11:09 UTC, oihane requested changes, later dismissed
Revisa lo que te he puesto para solucionar el error de travis

2020-09-04 11:09 UTC, oihane commented on fleet_route_reports/models/fleet_route.py
> +        return self.display_name
Estas sobreescribiendo la función y estas rompiendo los tests

2020-09-04 12:25 UTC, adrianrevilla009 commented
Modificado la plantilla de incidencias mediante herencia.
Por cada parada saca sus incidencias realizadas en el día actual.

Tengo un problema, y es que al heredar una plantilla y meter cambios vía xpath se modifica la plantilla original también. Como hago para que esto no pase?

2020-09-04 12:36 UTC, anajuaristi approved these changes

2020-09-04 12:37 UTC, merged