[ADD] fleet_route_school
avanzosc/odoo-addons pull request #922
Opened 2020-07-21 10:11 UTC by adrianrevilla009

Añadido el campo route_product_id al modelo fleet_route_stop_passenger.

2020-07-21 10:48 UTC, alfredoavanzosc reviewed
:+1:

2020-07-21 11:58 UTC, oihane requested changes
Revisa la vista, para que el diff solo muestre los cambios reales

![image](https://user-images.githubusercontent.com/2323616/88052277-50202300-cb5a-11ea-8f57-2c387466701a.png)

2020-07-22 06:55 UTC, adrianrevilla009 commented
Formateado @avanzosc/developers

2020-07-22 08:45 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                    options="{'no_create': True, 'no_open': True}" />
cambios no necesarios, revierte

2020-07-22 08:45 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +        model="ir.ui.view">
revierte el cambio

2020-07-22 08:45 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                    options="{'no_create': True}" />
Deja como estaba

2020-07-22 08:46 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +        model="ir.ui.view">
No tiene porque haber salto de linea, es xml

2020-07-22 08:46 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                            options="{'no_create': True}" />
No es necesario este cambio

2020-07-22 08:46 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                            options="{'no_create': True, 'no_open': True}" />
**domain** y **options**, deben quedar a la altura de **name**

2020-07-22 08:47 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                            options="{'no_create': True}" />
Si no "cambias" nada, esto es innecesario

2020-07-22 08:50 UTC, oihane requested changes

2020-07-22 08:50 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +        model="ir.ui.view">
Lo mismo

2020-07-22 08:50 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                        string="Passenger" />
Y otra vez

2020-07-22 08:50 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                        string="Route Stop" />
otra vez

2020-07-22 08:50 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +                        string="Route" />
y otra vez

2020-07-22 08:50 UTC, oihane commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
>  </odoo>
Lo mismo, no estas cambiando nada realmente, en cada PR puedes ver la "diferencia" que hay entre lo que había y lo que has subido, revisalo primero para ver que has cambiado y si realmente has cambiado. Si no deberás de deshacer el cambio.

2020-07-22 09:29 UTC, adrianrevilla009 commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
>  </odoo>
modificado el PR @oihane

2020-07-22 12:38 UTC, anajuaristi approved these changes

2020-07-22 12:38 UTC, anajuaristi commented on fleet_route_school/views/fleet_route_stop_passenger_view.xml
> +			<tree>
Te está volviendo a pasar lo mismo de siempre con los tabuladores y los espacios. Son 4 espacios. No un tabulador, ni un único espacio. 
Por favor ajusta el editor a como te pone Dani en otro PR y resube los cambios.
Gracias

2020-07-22 14:01 UTC, oihane commented on fleet_route_school/i18n/eu_ES.po
> +msgstr "Ibilbide productua"
en euskera será Produktua, con K

2020-07-23 07:14 UTC, adrianrevilla009 commented on fleet_route_school/i18n/eu_ES.po
> +msgstr "Ibilbide productua"
modificado @oihane

2020-08-05 13:33 UTC, oihane approved these changes

2020-08-05 13:33 UTC, merged