[IMP] fleet_route_support
avanzosc/odoo-addons pull request #950
Opened 2020-08-25 08:39 UTC by adrianrevilla009

CLM8454 - Reapertura CLM7659 Ajustes incidencias de autobús COAS 20200330
@avanzosc/developers

2020-08-25 11:13 UTC, oihane requested changes, later dismissed
Tienes que crear un many2many con las paradas de las que se puede dar de baja, y luego filtrar las paradas por ese mismo campo
Tienes un ejemplo en https://github.com/avanzosc/odoo-addons/blob/12.0/contacts_school_permission/models/res_partner_permission.py#L19

```python
    allowed_signer_ids = fields.Many2many(
        comodel_name='res.partner', string='Allowed Signers',
        compute='_compute_allowed_signer_ids', store=True)
    signer_id = fields.Many2one(
        comodel_name='res.partner', string='Signed by',
        domain="[('id', 'in', allowed_signer_ids)]")
```

2020-09-02 11:29 UTC, adrianrevilla009 commented
Añadido el OR para la condicional:
((start_date < date) || (start_date = False)) && ((end_date > date) || (end_date = False))

2020-09-03 12:39 UTC, anajuaristi approved these changes

2020-09-03 12:39 UTC, anajuaristi commented on fleet_route_support/models/fleet_route_support.py
> +             ("start_date", "<", self.date),
Contempla también que las fechas de inicio y fin del alta del niño pueden estar vacías.
Es decir  ("start_date", "<", self.date) or  is_null("start_date") (no sé la sintaxis)

2020-09-03 13:00 UTC, anajuaristi approved these changes

2020-09-03 13:06 UTC, Daniel-CA approved these changes

2020-09-03 14:59 UTC, merged