[FIX] calendar_school
avanzosc/odoo-addons pull request #995
Opened 2020-10-01 08:53 UTC by adrianrevilla009

CLM8682
Ajustes en el módulo reuniones

2020-10-01 10:55 UTC, oihane requested changes

2020-10-01 10:55 UTC, oihane commented on calendar_school/models/hr_employee.py
> +        action = self.env.ref('calendar_school.tutoring_calendar_event_action')
No debes cambiar la acción que ejecuta, ya que la de calendario abre las reuniones "en general" y la que estas poniendo solo las "ordinarias"

2020-10-01 10:55 UTC, oihane commented on calendar_school/models/hr_employee_supervised_year.py
> +        action = self.env.ref('calendar_school.tutoring_calendar_event_action')
Lo dicho anteriormente

2020-10-01 10:55 UTC, oihane commented on calendar_school/models/res_partner.py
> +        action = self.env.ref('calendar_school.tutoring_calendar_event_action')
Lo dicho anteriormente

2020-10-01 10:55 UTC, oihane commented on calendar_school/models/hr_employee_supervised_year.py
> +                ('stop', '<=', start.replace(hour=23, minute=59, second=59))]
si lo que no tiene que tener es una en el mismo dia, lo que haria simplemente es

```python
('start_date', '=', date)
```

Si hay que hacer conversion

```python
fields.Date.to_date(date)
```

2020-10-01 11:40 UTC, adrianrevilla009 commented on calendar_school/models/hr_employee.py
> +        action = self.env.ref('calendar_school.tutoring_calendar_event_action')
Esto lo hago para que cuando entres desde el button_show_meetings entres directo al tree y no al calendario. Te refieres a que el action definido tendría que ser el siguiente?
calendar.action_view_calendar_event_tree

2020-10-01 11:41 UTC, adrianrevilla009 commented on calendar_school/models/hr_employee_supervised_year.py
> +                ('stop', '<=', start.replace(hour=23, minute=59, second=59))]
De acuerdo.

2020-10-02 08:52 UTC, adrianrevilla009 commented
He modificado los valores del action mediante herencia.
<field name="view_mode">tree,calendar,form</field>
<field name="view_id" ref="view_calendar_event_tree"/>
También las prioridades de los action_view para tree y calendar.
<field name="sequence" eval="1"/>
Y sigue sin cambiar el orden de las vistas.

2020-10-02 12:19 UTC, oihane requested changes
Tienes que MODIFICAR lo que existe NO CREAR nuevos.

2020-10-02 12:19 UTC, oihane commented on calendar_school/views/calendar_event_view.xml
> +    </record>
has creado una nueva accion no modificado la que existe

```xml
<record id="calendar.action_calendar_event" model="ir.actions.act_window">
    <field name="view_mode">tree,form,calendar</field>
    <field name="view_id" ref="calendar.view_calendar_event_tree">
</record>

2020-10-02 12:19 UTC, oihane commented on calendar_school/views/calendar_event_view.xml
> +    </record>
```xml
    <record id="calendar.action_view_calendar_event_calendar" model="ir.actions.act_window.view">
        <field name="sequence" eval="4"/>
    </record>

```

2020-10-13 06:40 UTC, alfredoavanzosc approved these changes
:+1

2020-10-13 08:53 UTC, adrianrevilla009 commented
Lo he resubido porque me había cargado el contenido del anterior PR con el nuevo que había hecho.

2020-10-13 08:58 UTC, anajuaristi approved these changes

2020-10-13 08:58 UTC, Daniel-CA approved these changes

2020-10-23 10:43 UTC, oihane commented
Cambios añadidos en otro PR, cierro este

2020-10-23 10:43 UTC, closed without merging